// Generated by CoffeeScript 1.3.3
var embedder, inject_pinboard, inject_timeline, months, t_pinboard, twelve_hour;

window.echo_tweets = function(tweets) {
  var tweet, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = tweets.length; _i < _len; _i++) {
    tweet = tweets[_i];
    _results.push(console.log(tweet.text));
  }
  return _results;
};

embedder = function(html_id, width) {
  var embed;
  return embed = function(tweets) {
    if (tweets.length === 0) {
      $("head").append("<script type=\"text/javascript\"             src=\"http://platform.twitter.com/widgets.js\"></script>");
    }
    return $.ajax({
      url: "http://api.twitter.com/1/statuses/oembed.json",
      type: 'jsonp',
      data: {
        id: tweets.pop().id_str,
        maxwidth: width
      },
      success: function(oembed) {
        $("#" + html_id).append(oembed.html);
        return embed(tweets);
      }
    });
  };
};

inject_timeline = function(html_id, username, count, width) {
  if (width == null) {
    width = 300;
  }
  return tweet_timeline(embedder(html_id, width), username, count);
};

months = ["Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sep", "Nov", "Dec"];

twelve_hour = function(_24_hour) {
  var hour;
  hour = parseInt(_24_hour);
  hour += 1;
  if (hour > 12) {
    return ["" + (hour - 12), "pm"];
  }
  return ["" + hour, "am"];
};

Handlebars.registerHelper("date", function(date) {
  var dt, hour, suffix, _ref;
  dt = new Date(date);
  _ref = twelve_hour(dt.getHours()), hour = _ref[0], suffix = _ref[1];
  return "" + months[dt.getMonth()] + " " + (dt.getDate()) + ",             " + (dt.getFullYear()) + " " + hour + "            " + (dt.getMinutes()) + " " + suffix;
});

t_pinboard = Handlebars.compile($("pinboard-template").html());

inject_pinboard = function(view) {
  return $.ajax({
    async: false,
    url: "http://feeds.pinboard.in/json/" + view,
    type: "json",
    success: function(link_items) {
      var link_item, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = link_items.length; _i < _len; _i++) {
        link_item = link_items[_i];
        _results.push($("#linkroll").append(t_pinboard(link_item)));
      }
      return _results;
    }
  });
};

inject_pinboard("u:joshkunz");
