// Generated by CoffeeScript 1.3.3
(function() {
  var embedder, inject_timeline;

  window.echo_tweets = function(tweets) {
    var tweet, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = tweets.length; _i < _len; _i++) {
      tweet = tweets[_i];
      _results.push(console.log(tweet.text));
    }
    return _results;
  };

  embedder = function(tweets) {
    if (tweets.length === 0) {
      $("head").append("<script type=\"text/javascript\"         src=\"http://platform.twitter.com/widgets.js\"></script>");
    }
    return $.ajax({
      url: "http://api.twitter.com/1/statuses/oembed.json",
      type: 'jsonp',
      data: {
        id: tweets.pop().id_str,
        maxwidth: width
      },
      success: function(oembed) {
        $("#" + html_id).append(oembed.html);
        return embedder(tweets, callback);
      }
    });
  };

  inject_timeline = function(html_id, username, count, width) {
    if (width == null) {
      width = 300;
    }
    return tweet_timeline(embedder, username, count);
  };

}).call(this);
